### PR TITLE
Updated the benches to allow multiple executions

### PR DESCRIPTION
**Pull request by mattiasdrp**
The displayed result is the mean of all the computed results

### CODE REVIEW

**Comment by samoht** [comment]
It's a good idea to add more iterations to reduce variance but it would be nice to not have to wait for 30 minutes to get a feedback. We can remove one or two existing benchmarks to avoid this.

It would also be a good idea to use mtime instead of systime (in a different PR).

**Comment by mattiasdrp** [comment]
Testing with 

```bash
dune exec -- ./bench/bench.exe --json --minimal --nb-exec n
```
| `n` | time |
| ------------- | ------------- |
| 1 |  155,22s = 3 min |
| 3 | 436,05s = 7 min |
| 5  | 763,81s = 12min  |

Do you have some preferences? The difference between 1 and 3 executions is not that huge

**Review by icristescu — APPROVED** [review]

**Comment by icristescu** [comment]
can you rebase it?

**Comment by mattiasdrp** [comment]
Done

**Comment by icristescu** [comment]
Thanks!

**Pull request merged**
