### PR TITLE
Index.rename should also rename the cached filename

### PR DESCRIPTION
**Pull request by samoht**
That doesn't change anything, but that makes the logs a bit prettier

### CODE REVIEW

**Comment by CraigFe** [comment]
What's the intended semantics of `rename`?

I would expect `~src` to be unusable after the rename has completed. (Or, for `~src` to be changed in place and to take a `~dst:string` rather than a `~dst:IO`.)

**Comment by samoht** [comment]
Rename currently just changes `src` in place.

**Comment by samoht** [comment]
I'm in favour of merging this one as it improves the debug messages (and will be needed if we ever want to unlink files). A proper API refactoring should probably happen later on.

**Comment by CraigFe** [comment]
As mentioned offline, I think any use of `src` after the rename is likely to cause trouble. Where does this improve the logs? The only use I see is [here](https://github.com/mirage/index/blob/master/src/index.ml#L624), and the `src` isn't used after that point.

**Comment by samoht** [comment]
It helped me to find the issue with the shares write buffers :-)

**Comment by CraigFe** [comment]
CI failure unrelated. (The Ubuntu 20.04 runner doesn't support depexts properly.)

**Pull request merged**
